#!/bin/sh

# rust (ripgrep)
if [ -d "$HOME/.cargo/bin" ]; then
    PATH="$HOME/.cargo/bin:$PATH"
fi

if [ $(type nvim > /dev/null; echo $?) -eq 0 ]; then
    export NVIM_PYTHON_LOG_FILE="/tmp/log"
    export NVIM_PYTHON_LOG_LEVEL="DEBUG"
fi

