
if has('gui_running') " for gvim
    set guioptions=gita

    if has('win32') " for Kaoriya vim
        silent set renderoptions=type:directx,renmode:5
    endif

    if has('win32')
        try
            set guifont=Cica:h9
            if IsPlugged('vim-devicons')
                silent UseDevicons
            endif
        catch
            set guifont=Consolas:h9
        endtry
    else
        silent set guifont=Cica\ 9
        if IsPlugged('vim-devicons')
            silent UseDevicons
        endif
    endif
elseif exists('g:GuiLoaded') " for neovim-qt
    set termguicolors
    try
        silent GuiFont! Cica:h9
        silent GuiLinespace 0

        " change font size with C-mousewheel
        silent! nmap <unique> <silent> <C-ScrollWheelUp>   :<C-u>call ResizeFontSize(+1)<CR>
        silent! nmap <unique> <silent> <C-ScrollWheelDown> :<C-u>call ResizeFontSize(-1)<CR>
        fun! ResizeFontSize(add)
            let current = substitute(execute('GuiFont'), '\n', '', 'g')
            if !exists('s:keep')
                let s:keep = [&lines, &columns]
            endif
            let before = substitute(current, '\v[^0-9]*(\d{1,})$', '\1', '')
            let after = before + a:add
            if after < 1
                let after = 1
            endif
            silent exec 'GuiFont! ' . substitute(current, '\v'.before.'$', after, '')
            let [&lines, &columns] = s:keep
        endfun
        " if IsPlugged('vim-devicons')
        "     silent UseDevicons
        " endif
    endtry
endif

if IsPlugged('onedark.vim')
    color onedark
else
    set background=dark
endif
