
if has('gui_running') " for gvim
    set guioptions-=T
    set guioptions-=r
    set guioptions-=R
    set guioptions-=l
    set guioptions-=L
    set guioptions-=b
    set guioptions-=e
    set guioptions+=a
    set guioptions-=m

    if has('win32') " for Kaoriya vim
        silent set renderoptions=type:directx,renmode:5
    endif

    if has('win32')
        try
            set guifont=Cica:h9
        catch
            set guifont=Consolas:h9
        endtry
    else
        silent set guifont=Cica\ 9
    endif
elseif exists('g:GuiLoaded') " for neovim-qt
    set termguicolors
    silent GuiFont! Cica:h9
    silent GuiLinespace 0
endif

if IsPlugged('onedark.vim')
    color onedark
else
    set background=dark
endif
